### ISSUE TITLE
vuex.d.ts -> vue.d.ts

### ISSUE THREAD

**Issue by fateevv** [ClickerMonkey/vuex-typescript-interface#4]
It seems that [the import](https://github.com/ClickerMonkey/vuex-typescript-interface/blob/master/index.d.ts#L4) is a bit broken.
It causes type errors in a `main.ts` entry point when injecting a store instance into the root Vue component.

**Comment by ClickerMonkey** [comment]
What version of TypeScript, Vue and Vuex?

**Comment by fateevv** [comment]
Latest versions: TypeScript 3.4.5, Vue 2.6.10 and Vuex 3.1.1

**Comment by ClickerMonkey** [comment]
What is the exact error you're getting?

I'm not having any problems.

Are you importing from `vuex-typescript-interface` instead of `vuex` ?

Everywhere, or just in some places?

**Comment by fateevv** [comment]
I just created a new project from latest vue-cli for clean experiment. I picked Vuex, Vue-router, TypeScript (with class component syntax) and ESLint. Then I added a module to store and described it as shown in readme. The only import of Vuex is in `store.ts` and it is from `vuex-typescript-interface`.
Finally I got an error when I was trying to build the project: 
```
(property) store: Store<Root>
Argument of type '{ router: VueRouter; store: Store<Root>; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Object literal may only specify known properties, and 'store' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.ts(2345)
```
My guess was that root `vuex.d.ts` file in your package (where augmenting of Vue is made) should be renamed to `vue.d.ts` as in initial `vuex` package.

**Comment by ClickerMonkey** [comment]
I have no idea how I looked at that multiple times and missed it!

I'm surprised my TypeScript didn't complain, that's a little worrying.

I've published version 1.0.1 to NPM

**Comment by fateevv** [comment]
Thank you, now it works! You made a very useful tool, It's a pity that I haven't found it before.

**Comment by ClickerMonkey** [comment]
Thanks, hopefully I'll have namespace support sometime soon!
